# Generated by Django 3.2.25 on 2026-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('multiple_choice', '多选题'), ('true_false', '判断题'), ('fill_blank', '填空题'), ('essay', '简答题')], max_length=20, verbose_name='题型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.TextField(blank=True, default='{}', help_text='JSON格式，如：{"A": "选项1", "B": "选项2"}', verbose_name='选项')),
                ('answer', models.TextField(verbose_name='答案')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='解析')),
                ('knowledge_point', models.CharField(blank=True, max_length=200, null=True, verbose_name='知识点')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '较简单'), (3, '中等'), (4, '较难'), (5, '困难')], default=3, verbose_name='难度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
