# Generated by Django 3.2.25 on 2026-05-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_questionai'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=5, verbose_name='分值'),
        ),
        migrations.AddField(
            model_name='questionai',
            name='score',
            field=models.IntegerField(default=5, verbose_name='分值'),
        ),
    ]
