# Generated by Django 6.0.4 on 2026-05-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_question_score'),
        ('question_bank', '0004_auto_20260518_2121'),
    ]

    operations = [
    ]
