# Generated by Django 6.0.4 on 2026-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0005_merge_0003_question_score_0004_auto_20260518_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=5, verbose_name='分值'),
        ),
    ]
