# Generated by Django 3.2.25 on 2026-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(verbose_name='学生答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='得分')),
            ],
            options={
                'verbose_name': '答题详情',
                'verbose_name_plural': '答题详情',
                'db_table': 'answer_details',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='试卷名称')),
                ('total_score', models.DecimalField(decimal_places=1, default=100, max_digits=5, verbose_name='总分')),
                ('duration', models.IntegerField(default=120, verbose_name='时长(分钟)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'exam_papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, default=10, max_digits=5, verbose_name='分值')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'db_table': 'exam_paper_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='得分')),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('submitted', '已提交'), ('graded', '已评分')], default='ongoing', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'db_table': 'exam_records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_answer', models.TextField(verbose_name='错误答案')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='是否掌握')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('mastered_at', models.DateTimeField(blank=True, null=True, verbose_name='掌握时间')),
            ],
            options={
                'verbose_name': '错题本',
                'verbose_name_plural': '错题本',
                'db_table': 'wrong_questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
