# Generated by Django 3.2.25 on 2026-04-13 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0001_initial'),
        ('exam_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_by_students', to='question_bank.question', verbose_name='题目'),
        ),
    ]
