# Generated by Django 3.2.25 on 2026-04-13 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_bank', '0001_initial'),
        ('users', '0001_initial'),
        ('exam_core', '0002_wrongquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='exam_core.exampaper', verbose_name='试卷'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='exampaperquestion',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='exam_core.exampaper', verbose_name='试卷'),
        ),
        migrations.AddField(
            model_name='exampaperquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='question_bank.question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_papers', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='target_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='users.class', verbose_name='目标班级'),
        ),
        migrations.AddField(
            model_name='answerdetail',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='question_bank.question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='answerdetail',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='exam_core.examrecord', verbose_name='考试记录'),
        ),
        migrations.AlterUniqueTogether(
            name='wrongquestion',
            unique_together={('student', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='examrecord',
            unique_together={('student', 'paper')},
        ),
        migrations.AlterUniqueTogether(
            name='exampaperquestion',
            unique_together={('paper', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='answerdetail',
            unique_together={('record', 'question')},
        ),
    ]
