# Generated by Django 6.0.5 on 2026-05-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='tab_switch_count',
            field=models.IntegerField(default=0, verbose_name='切屏次数'),
        ),
    ]
