# Generated by Django 6.0.4 on 2026-05-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0004_examrecord_tab_switch_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='is_practice',
            field=models.BooleanField(default=False, verbose_name='是否练习'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='question_count',
            field=models.IntegerField(default=0, verbose_name='题目数量'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='exam_core.exampaper', verbose_name='试卷'),
        ),
    ]
