# Generated by Django 3.2.25 on 2026-05-18 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_questionai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_core', '0005_add_practice_fields_to_examrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='source_id',
            field=models.IntegerField(blank=True, help_text='source_type=ai时指向question_ai.id', null=True, verbose_name='来源题目ID'),
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='source_type',
            field=models.CharField(choices=[('main', '主题库'), ('ai', 'AI练习库')], default='main', max_length=10, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_by_students', to='question_bank.question', verbose_name='题目'),
        ),
        migrations.AlterUniqueTogether(
            name='wrongquestion',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('main', '主题库'), ('ai', 'AI练习库')], default='main', max_length=10, verbose_name='来源')),
                ('question_id', models.IntegerField(help_text='指向question或question_ai的id', verbose_name='题目ID')),
                ('question_content', models.TextField(verbose_name='题目内容')),
                ('question_type', models.CharField(max_length=20, verbose_name='题型')),
                ('student_answer', models.TextField(verbose_name='学生答案')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('knowledge_point', models.CharField(blank=True, max_length=200, null=True, verbose_name='知识点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='做题时间')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='practice_records', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
                'db_table': 'practice_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
