# Generated by Django 6.0.5 on 2026-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0005_exampaper_end_time_exampaper_pass_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='is_practice',
            field=models.BooleanField(default=False, verbose_name='练习模式'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='question_count',
            field=models.IntegerField(default=0, verbose_name='题目数量'),
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='来源ID'),
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='source_type',
            field=models.CharField(default='main', max_length=10, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='wrong_answer',
            field=models.TextField(default='', verbose_name='错误答案'),
        ),
    ]
