# Generated by Django 6.0.4 on 2026-05-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0006_auto_20260518_1739'),
        ('exam_core', '0006_exampaper_end_time_examrecord_is_practice_and_more'),
    ]

    operations = [
    ]
