# Generated by Django 6.0.4 on 2026-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0007_merge_20260520_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='pass_score',
            field=models.DecimalField(decimal_places=1, default=60, max_digits=5, verbose_name='及格分数'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='wrong_answer',
            field=models.TextField(verbose_name='错误答案'),
        ),
    ]
