# Generated by Django 6.0.4 on 2026-06-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0009_studysession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerdetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='answerdetail',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='exam_core.examrecord', verbose_name='考试记录'),
        ),
    ]
