# Generated by Django 6.0.4 on 2026-06-07 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0010_alter_answerdetail_unique_together_and_more'),
        ('question_bank', '0006_alter_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='answerdetail',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='exam_core.examrecord', verbose_name='考试记录'),
        ),
        migrations.AlterUniqueTogether(
            name='answerdetail',
            unique_together={('record', 'question')},
        ),
    ]
