# Generated by Django 6.0.5 on 2026-06-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0011_exampaper_end_time_alter_answerdetail_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='is_completed',
            field=models.BooleanField(default=True, verbose_name='是否完成'),
        ),
    ]
