# Generated by Django 3.2.25 on 2026-05-18 09:39
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='examrecord',
                    name='exam_paper',
                ),
                migrations.RemoveField(
                    model_name='examrecord',
                    name='student',
                ),
                migrations.RemoveField(
                    model_name='wrongquestion',
                    name='question',
                ),
                migrations.RemoveField(
                    model_name='wrongquestion',
                    name='student',
                ),
                migrations.DeleteModel(
                    name='AnswerDetail',
                ),
                migrations.DeleteModel(
                    name='ExamRecord',
                ),
                migrations.DeleteModel(
                    name='WrongQuestion',
                ),
            ]
        ),
    ]
